x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"

services:
  l1dtl:
    image: ericlee42/metis:${DTL_IMAGE_TAG:-dtl-3}
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - l1dtl-data:/data
    env_file:
      - ./l1dtl.env
    environment:
      - DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=${DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT}
    healthcheck:
      test: ["CMD-SHELL", "curl http://127.0.0.1:7878"]
      interval: 5s
      timeout: 3s
      retries: 6
    <<: *logging

  l2geth:
    image: ericlee42/metis:${L2GETH_IMAGE_TAG:-l2geth-5}
    restart: unless-stopped
    stop_grace_period: 2m
    env_file:
      - ./l2geth.env
    depends_on:
      l1dtl:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl http://127.0.0.1:8545"]
      interval: 5s
      timeout: 3s
      retries: 6
    environment:
      GCMODE: ${GCMODE}
      VERBOSITY: ${VERBOSITY}
    volumes:
      - l2geth-data:/root/.ethereum
    <<: *logging

  metis-replica-healthcheck:
    image: ethereumoptimism/replica-healthcheck:${HC_IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      HEALTHCHECK__REFERENCE_RPC_PROVIDER: ${HEALTHCHECK__REFERENCE_RPC_PROVIDER}
      HEALTHCHECK__TARGET_RPC_PROVIDER: ${HEALTHCHECK__TARGET_RPC_PROVIDER}
      REPLICA_HEALTHCHECK__ETH_NETWORK: ${REPLICA_HEALTHCHECK__ETH_NETWORK}
    <<: *logging

volumes:
  l1dtl-data:
  l2geth-data:
